<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Base Classes and Extensions for the creating, modifying and handling from a data store.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Audacia.CodeAnalysis" Version="1.12.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Audacia.Core" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\package-icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
