<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<Description>Base helper interfaces for auditing etc.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Audacia.CodeAnalysis" Version="1.12.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\package-icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
