<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Command pattern implementation with support for persisting changes to a database</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Audacia.CodeAnalysis" Version="1.12.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Audacia.Commands" Version="1.1.3" />
    <PackageReference Include="Audacia.Core" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Audacia.DataAccess\Audacia.DataAccess.csproj" />
  </ItemGroup>
</Project>
